### ISSUE TITLE
Possibility to disable click?

### ISSUE THREAD

**Issue by cxammar** [mirari/vue3-viewer#4]
Hello I want to be able to disable clicking on the viewer. So that when the user clicks there's no action from the viewer. Is It possible?

**Comment by mirari** [comment]
Use the `filter` option.
Refer to this example:
https://codepen.io/mirari/pen/mdWqpwa

**Comment by cxammar** [comment]
Thanks I will review!

**Comment by cxammar** [comment]
Got it working. Many thanks!
